### ISSUE TITLE
打包运行问题

### ISSUE THREAD

**Issue by 6337215** [defghy/git-split-demo#7]
试运行了项目，main文件夹中执行npm run prod 打包完项目后，生成的public中的dist文件夹中怎么也找不到html文件，请问这个打包后的文件该如何运行？

**Comment by defghy** [comment]
这个项目是我从公司的代码里面抽取出来的。实际prod是跑不起来的，只有测试环境可以看下；线上发布只能自己实现下了。
由于现在微前端已经成为业界趋势，因此这个项目的功能就只是参考下而已，如果想真正取用可以看看大厂放出来的微前端框架，比如single-spa。
